apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace:  my-app-namespace
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80       # Service port
    targetPort: 80 # Target port on the container
  type: NodePort # Use LoadBalancer, NodePort, or ClusterIP
